# Generated by Django 4.1.1 on 2023-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('park_id', models.CharField(max_length=100, verbose_name='ID парка')),
                ('api_key', models.CharField(max_length=100, verbose_name='API ключ')),
                ('client_id', models.CharField(max_length=100, verbose_name='ID клиента')),
            ],
            options={
                'verbose_name': 'такси парк',
                'verbose_name_plural': 'Такси парки',
            },
        ),
    ]
