# Generated by Django 4.1.1 on 2023-10-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipark',
            name='work_rule_id',
            field=models.CharField(default='123321', max_length=100, verbose_name='ID правил'),
            preserve_default=False,
        ),
    ]
