# Generated by Django 4.1.1 on 2023-10-29 16:46

import control_room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0002_taxipark_work_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipark',
            name='taxi_park_type',
            field=control_room.models.ChoiceArrayField(base_field=models.CharField(choices=[('taxi', 'Такси'), ('auto_courier', 'Авто курьер'), ('foot_courier', 'Пеший или Вело курьер'), ('cargo_transportation', 'Грузоперевозки'), ('moto_courier', 'Мото курьер')], max_length=25), blank=True, default=list, size=None, verbose_name='Типы такси парка'),
        ),
    ]
