# Generated by Django 4.1.1 on 2023-10-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0003_taxipark_taxi_park_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxipark',
            name='work_rule_id',
        ),
    ]
